## NumpyLibrary Example

In [1]:
import numpy as np

In [5]:
x = np.array([1, 2, 3], dtype='f')
print(x.dtype)
print(x)

float32
[1. 2. 3.]


In [6]:
x = np.array([1, 2, 3], dtype='i2')
print(x.dtype)
x

int16


array([1, 2, 3], dtype=int16)

In [8]:
a = np.array([[1, 2], [3, 4]])
print (a)
print(a.shape, a.ndim)

[[1 2]
 [3 4]]
(2, 2) 2


In [10]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a)
print("*" * 10)
b = a.reshape(3,2)
print (b)

(2, 3)
[[1 2 3]
 [4 5 6]]
**********
[[1 2]
 [3 4]
 [5 6]]


In [14]:
x = np.empty([3,2], dtype=int)
print(x)

[[ 73728086         0]
 [        0         0]
 [        1 544826728]]


In [16]:
x = np.zeros((3,2), dtype="int")
print(x)

[[0 0]
 [0 0]
 [0 0]]


In [19]:
# x = np.arange(10,20) #10은 포함 20은 포함x
x = np.arange(10,20,2) # from, to , step
print(x)

[10 12 14 16 18]


In [22]:
# x = np.linspace(10,20, 5, endpoint = True) # 10에서 20까지(10, 20 둘 다 포함)를 한단계의 값을
x = np.linspace(10,20, 5, endpoint = False)
print (x)

[10. 12. 14. 16. 18.]


In [23]:
a = np.arange(10)
s = slice(2,7,2)
print (a[s])

[2 4 6]


In [24]:
a = np.arange(10)
b = a[2:7:2]
print (b)

[2 4 6]


In [25]:
a = np.arange(10)
b = a[5]
print (b)

5


In [31]:
##### a = np.arange(10)
print (a[2:]) # 2 ~ 끝
print (a[:5]) # 처음 ~ 5

[2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [32]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0,1,2], [0,1,0]]
print (y)

[1 4 5]


In [35]:
x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
# print(x)
# x > 5
print(x[x > 5]) # boolean indexing

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [42]:
a = np.array([np.nan, 1,2,np.nan,3,4,5])
# print(a)
# print(np.isnan(a))
# print(~np.isnan(a))
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]
